version: "3.6"

services:
  webapp:
    container_name: isec_react_soup_letter
    build:
      context: .
    restart: unless-stopped
    command: npm start
    env_file: ./.env
    ports:
      - $PORT:$PORT
    expose:
    - $PORT

networks:
  default:
    external: true
    name: nginx_production_default